drop table if exists planets CASCADE;
drop table if exists stars CASCADE;
create table planets (
    id                bigint generated by default as identity,
    detection         varchar(255),
    habitable_zone    boolean,
    name              varchar(255) not null,
    confirmed         boolean,
    year_of_discovery integer check (year_of_discovery >= 1995),
    star_id           bigint,
    primary key (id)
);
create table stars (
    id                      bigint generated by default as identity,
    distance_in_light_years double,
    mass_sun                double,
    name                    varchar(255) not null,
    radius_sun              double,
    temperature_in_kelvin   integer,
    primary key (id)
);
alter table planets
    add constraint UK_b19q51pod68r7255u76mkayy4 unique (name);
alter table stars
    add constraint UK_epb49sf8a41eba9qba3nhjof5 unique (name);
alter table planets
    add constraint FKl1i5l50704o2j1bu62xw1qo34 foreign key (star_id) references stars;