drop table if exists moons CASCADE;
create table moons (
    id        bigint generated by default as identity,
    name      varchar(255) not null,
    confirmed boolean,
    planet_id bigint,
    primary key (id)
);
alter table moons
    add constraint UK_7q1f0jexvama4d1iwg6f8wspo unique (name);
alter table moons
    add constraint FK1bllnyryaoi7flc5keoa7iqyj foreign key (planet_id) references planets;