INSERT INTO Stars (NAME, DISTANCE_IN_LIGHT_YEARS, RADIUS_SUN, MASS_SUN, TEMPERATURE_IN_KELVIN)
VALUES ('TRAPPIST-1', 39, 0.117, 0.08, 2560);
INSERT INTO Stars (NAME, DISTANCE_IN_LIGHT_YEARS, RADIUS_SUN, MASS_SUN, TEMPERATURE_IN_KELVIN)
VALUES ('Proxima Centauri', 4.2, 0.141, 0.12, 3050);
INSERT INTO Stars (NAME, DISTANCE_IN_LIGHT_YEARS, RADIUS_SUN, MASS_SUN, TEMPERATURE_IN_KELVIN)
VALUES ('Kepler-62', 990, 0.64, 0.69, 4925);
INSERT INTO Stars (NAME, DISTANCE_IN_LIGHT_YEARS, RADIUS_SUN, MASS_SUN, TEMPERATURE_IN_KELVIN)
VALUES ('Kepler-1625', 8000, 0.94, 0.96, 5677);
INSERT INTO Stars (NAME, DISTANCE_IN_LIGHT_YEARS, RADIUS_SUN, MASS_SUN, TEMPERATURE_IN_KELVIN)
VALUES ('J1407', 434, 0.99, 0.9, 4400);

INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', FALSE, 'Kepler-1625 b', TRUE, 2016, 4);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', FALSE, 'J1407 b', TRUE, 2012, 5);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', FALSE, 'TRAPPIST-1 b', TRUE, 2016, 1);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', FALSE, 'TRAPPIST-1 c', TRUE, 2016, 1);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', TRUE, 'TRAPPIST-1 d', TRUE, 2016, 1);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', TRUE, 'TRAPPIST-1 e', TRUE, 2017, 1);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', TRUE, 'TRAPPIST-1 f', TRUE, 2017, 1);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', TRUE, 'TRAPPIST-1 g', TRUE, 2017, 1);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', FALSE, 'TRAPPIST-1 h', TRUE, 2017, 1);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('RADIAL_VELOCITY', TRUE, 'Proxima Centauri b', TRUE, 2016, 2);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('RADIAL_VELOCITY', FALSE, 'Proxima Centauri c', TRUE, 2019, 2);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', FALSE, 'Kepler-62 b', TRUE, 2013, 3);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', fALSE, 'Kepler-62 c', TRUE, 2013, 3);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', FALSE, 'Kepler-62 d', TRUE, 2013, 3);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', TRUE, 'Kepler-62 e', TRUE, 2013, 3);
INSERT INTO Planets (DETECTION, HABITABLE_ZONE, NAME, CONFIRMED, YEAR_OF_DISCOVERY, STAR_ID)
VALUES ('PRIMARY_TRANSIT', TRUE, 'Kepler-62 f', TRUE, 2013, 3);

INSERT INTO Moons (NAME, CONFIRMED, planet_id)
VALUES ('Kepler-1625 b I', FALSE, 1);
INSERT INTO Moons (NAME, CONFIRMED, planet_id)
VALUES ('J1407 b I', FALSE, 2);
INSERT INTO Moons (NAME, CONFIRMED, planet_id)
VALUES ('J1407 b II', FALSE, 2);